### ISSUE TITLE
Cannot read property 'ts' of undefined` (undefined = mixGlob)

### ISSUE THREAD

**Issue by Venipa** [MohamedLamineAllal/laravel-mix-glob#1]
did exactly as told, using latest laravel-mix
`TypeError: Cannot read property 'ts' of undefined`

**Comment by Venipa** [comment]
though that was said that the mapping is defaulted it is not.

**Comment by MohamedLamineAllal** [comment]
@Venipa Sorry didn't see that. Can you provide a log. Where the error is. For the mapping it is provided by default. By function mapping. {ts: {mapExt: 'js'}}. I confirm that. I have no problem with ts. In linux. And that before the changment and the features that i come to add. Not published yet. I will tomorrow. Check the doc again as it will be updated. For the bug above i really like to get more details so i can work on it. Error log + your webpack.mix.js config. Looking forward.

**Comment by MohamedLamineAllal** [comment]
closed as it's seem to work. And there is no more data.  (@Venipa  waiting for your data)

**Comment by iamntz** [comment]
@MohamedLamineAllal: i have the exact same issue (althoug is not TS related):


```
// the complete webpack.mix.js file
const mix = require('laravel-mix');
const MixGlob = require('laravel-mix-glob');


const mix2 = MixGlob({mix})

console.log(mix2);
console.log('=======================');
```

What I expect is to see that `mix2` be anything but... undefined:

```
  MixGlob:debug   'npm_config_cache_min',
  MixGlob:debug   'npm_config_cafile',
  MixGlob:debug   'npm_config_cert',
  MixGlob:debug   'npm_config_cidr',
  MixGlob:debug   'npm_config_color',
  MixGlob:debug   ... 203 more items ] +7ms
  MixGlob Mix glob +0ms
undefined
=======================
```

From this point on, it's obvious that any method will fail.

**Comment by donotfold** [comment]
I had the same issue. You have to add the `new` keyword to fix it.

Your example:
```
const mix = require('laravel-mix');
const MixGlob = require('laravel-mix-glob');

const mix2 = new MixGlob({ mix })
console.log(mix2);
```

This should log the result as you expected and execute the code without an error.

**Comment by MohamedLamineAllal** [comment]
Sorry folks i was busy and i didn't check. I just updated the documentation as by this issue. 
https://github.com/MohamedLamineAllal/laravel-mix-glob/issues/5#issuecomment-537991979
It was my stupid mistake. Within the doc there were part where i used `new MixGlob()` and in other i forget `new`. It's updated now.

**Comment by MohamedLamineAllal** [comment]
@donotfold @iamntz would you be interested to be added as contributors. Having more hands will be appreciated. And you'll be more free to help and add things.
