### ISSUE TITLE
.version()

### ISSUE THREAD

**Issue by RMK147** [MohamedLamineAllal/laravel-mix-glob#44]
Hello,

I'm having issues when using .version() in the following for example:

`mixGlob.sass('app/Modules/**/Resources/assets/admin/sass/*.scss', 'public/css')
    .version();`

Is this not supported or am I using it incorrectly?

**Comment by MohamedLamineAllal** [comment]
Hello !

laravel-mix-glob as is now! Through it's normal api it extends all methods to support globs! Only methods that take files are to be taken! And anything else like version() here  or extract(), are to be called from laravel mix instance directly!

That can be done as such

`mixGlob.sass('app/Modules/**/Resources/assets/admin/sass/*.scss', 'public/css') .mix('version')();`

I mentionned that in the documentation! you can check `use of laravel-mix itself` (CTRL + F)!

Now through that issue i got that i have to add direct support to those specific methods! (so in the next updated .version() should be usable directly! And all other methods of same nature!

I'm counting too to re-write the documentation to be simpler and of better experience!
