### ISSUE TITLE
CTRL+C to close doesn't work in NPM v7+

### ISSUE THREAD

**Issue by ahamilton9** [MohamedLamineAllal/laravel-mix-glob#64]
Not much more to mention. From NPM 7.0 onwards, my co-workers and I cannot use CTRL+C to close the processes.

**Comment by MohamedLamineAllal** [comment]
Hi. Let me investigate this. And note that i'm about to publish a v2 (full re-write). i'll check on that version.
Are you on macos or windows or ?

**Comment by MohamedLamineAllal** [comment]
On the v2 that im about to publish. On npm 9.2. On macos. Everything works fine.
The v2 have improved many things. Including the restart process and the kill and interupt process. Now it's more clean and efficient.
Make sure to check it out. I'll update you here as well once it's published.
